### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by qiankunshe** [chinakids/node-wiki#1]
#是否初始化过
  isFirst: true
 设置成true 时，启动到了    * re compile jade views 无法进行下去，无法启动，看了下mongodb也没找到初始化下的库
  Warning: missing space before text for line 20 of jade file "E:\opensource\js\node-wiki\views\layout"

 * re compile jade views

**Comment by chinakids** [comment]
抱歉我的 readme 有纰漏，请把isFirst改为 false 进行数据库初始化引导，然后重启服务就可以了

**Comment by qiankunshe** [comment]
还是不行，启动信息里面没有，监听的端口，无法访问项目，我试了 80 和3000 都不行的

**Comment by chinakids** [comment]
可以把终端输出的内容发出来么 
------------------ Original ------------------

**Comment by qiankunshe** [comment]
Warning: missing space before text for line 20 of jade file "E:\opensource\js\node-wiki\views\layout"

re compile jade views 
就只有这两个句话
对了我现在运行的环境是windows 
mongodb 是在别的服务器上，我确定可以访问，mongodb 版本是 3.0

**Comment by chinakids** [comment]
改成false后重启，能不能打开数据库设置页面？ 
------------------ Original ------------------

**Comment by qiankunshe** [comment]
是这样的，不知道服务器启动监听的端口，我用 http://127.0.0.1 和http://127.0.0.1:3000 都不能访问到数据设置页面的

**Comment by qiankunshe** [comment]
我看下 bin 下面的www 文件以为监听的是3000 发现也不是的

**Comment by qiankunshe** [comment]
晕死，找到了是3013

**Comment by qiankunshe** [comment]
最好在帮助文档和 控制台输出里面都加一下呀

**Comment by chinakids** [comment]
谢谢建议...数据库设置页面保存后还要重启服务器mongodb才能初始对应库

**Comment by qiankunshe** [comment]
ReferenceError: window is not defined
  at Object.<anonymous> (E:\opensource\js\node-wiki\node_modules\mermaid\src\d3.js:18:10)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (C:\Users\qiank\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\register.js:45:36)

**Comment by qiankunshe** [comment]
重启，直接出现了这个问题

**Comment by chinakids** [comment]
明天我试下在 window 部署吧，在 mac 上没问题.....唉

**Comment by qiankunshe** [comment]
嗯，谢谢了

**Comment by qiankunshe** [comment]
问题找到了，可以运行了 mermaid 的d3插件有问题，需要编译 本地库，node-pyg 编译报错了，但安装时又没提示，用npm 更新了一个最新的d3 就行了

**Comment by chinakids** [comment]
请把最新版本号回复我，我明天核查下依赖 
------------------ Original ------------------

**Comment by qiankunshe** [comment]
你英语好不 如果不错到这个 mermaid 插件的 git 下给他们说下， 升级下d3的依赖，我是直接把 mermaid 里面的d3 删除掉了， 使用 npm install d3 更新了一个 最新的 d3 ， 他原来使用的是"d3": "~3.4.13" ，最新的 d3 是 d3@3.5.6 node_modules\d3

**Comment by chinakids** [comment]
好
------------------ Original ------------------
