### ISSUE TITLE
新增后无法修改

### ISSUE THREAD

**Issue by qiankunshe** [chinakids/node-wiki#2]
新建文档，点击修改后， 没有显示新添加的内容， 显示 #Hello World

**Comment by chinakids** [comment]
进入编辑器了么？编辑器右下角有个保存

**Comment by qiankunshe** [comment]
这样的，我新增好一个文档保存成功了，在点击编辑时，不能取得当前要编译的内容

**Comment by qiankunshe** [comment]
刚看又没问题了，但是一直有个问题就是， 选择目录显示的都是 undefined/

**Comment by qiankunshe** [comment]
新建文档，点击修改后， 没有显示新添加的内容， 显示 #Hello World

我猜测这个问题是，http缓存导致的，但是没发现重现规则

**Comment by chinakids** [comment]
没理解你的意思，编辑器做了本地存储

**Comment by qiankunshe** [comment]
这个提问功能，发不了图片，不了用图片说最好了
